# Generated by Django 5.2.15 on 2026-08-15 18:26

import django.db.models.deletion
import vorin_blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown in cards and listings.')),
                ('content', models.TextField(blank=True, help_text='Legacy or rich HTML content for the post body.')),
                ('featured_image', models.URLField(blank=True, max_length=500, verbose_name='Thumbnail image URL')),
                ('featured_image_file', models.FileField(blank=True, upload_to=vorin_blog.utils.blog_upload_path, verbose_name='Thumbnail image file')),
                ('featured_image_alt', models.CharField(blank=True, max_length=255, verbose_name='Thumbnail image alt text')),
                ('header_image', models.URLField(blank=True, help_text='Wide banner image shown at the top of the detail page.', max_length=500, verbose_name='Header image URL')),
                ('header_image_file', models.FileField(blank=True, upload_to=vorin_blog.utils.blog_upload_path, verbose_name='Header image file')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Optional SEO title override.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Optional SEO description override.', max_length=160)),
                ('canonical_url', models.URLField(blank=True)),
                ('original_url', models.CharField(blank=True, help_text='Legacy source URL for redirects or imports.', max_length=500)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='vorin_blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='vorin_blog.tag')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PostBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('intro', 'Intro Paragraph'), ('text', 'Text Section'), ('image', 'Single Image'), ('image_pair', 'Two Images Side by Side'), ('quote', 'Pull Quote')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('body_text', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_file', models.FileField(blank=True, upload_to=vorin_blog.utils.blog_upload_path)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('image_caption', models.CharField(blank=True, max_length=300)),
                ('image2_url', models.URLField(blank=True, max_length=500)),
                ('image2_file', models.FileField(blank=True, upload_to=vorin_blog.utils.blog_upload_path)),
                ('image2_alt', models.CharField(blank=True, max_length=255)),
                ('quote_text', models.TextField(blank=True)),
                ('quote_author', models.CharField(blank=True, max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='vorin_blog.post')),
            ],
            options={
                'verbose_name': 'Story Section',
                'verbose_name_plural': 'Story Sections',
                'ordering': ['post', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_file', models.FileField(blank=True, upload_to=vorin_blog.utils.blog_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vorin_blog.post')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
